<?php return array(
    'root' => array(
        'pretty_version' => '4.0.0',
        'version' => '4.0.0.0',
        'type' => 'kirby-plugin',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => NULL,
        'name' => 'beebmx/kirby-blade',
        'dev' => true,
    ),
    'versions' => array(
        'beebmx/blade' => array(
            'pretty_version' => 'v1.5.2',
            'version' => '1.5.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../beebmx/blade',
            'aliases' => array(),
            'reference' => '8819f7f9ddf965936808a1d920ebcd6d926a2ac9',
            'dev_requirement' => true,
        ),
        'beebmx/kirby-blade' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'type' => 'kirby-plugin',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'brick/math' => array(
            'pretty_version' => '0.9.3',
            'version' => '0.9.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../brick/math',
            'aliases' => array(),
            'reference' => 'ca57d18f028f84f777b2168cd1911b0dee2343ae',
            'dev_requirement' => false,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'reference' => '8b7ff3e4b7de6b2c84da85637b59fd2880ecaa89',
            'dev_requirement' => true,
        ),
        'getkirby/composer-installer' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../getkirby/composer-installer',
            'aliases' => array(),
            'reference' => 'c98ece30bfba45be7ce457e1102d1b169d922f3d',
            'dev_requirement' => false,
        ),
        'illuminate/bus' => array(
            'pretty_version' => 'v9.19.0',
            'version' => '9.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/bus',
            'aliases' => array(),
            'reference' => '14060207ad684e6ea29b9ff3f349813d1d2a2a0a',
            'dev_requirement' => true,
        ),
        'illuminate/collections' => array(
            'pretty_version' => 'v9.19.0',
            'version' => '9.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/collections',
            'aliases' => array(),
            'reference' => '253cfce2bf469c340d2268bfbc31d4ad446a1fa7',
            'dev_requirement' => true,
        ),
        'illuminate/conditionable' => array(
            'pretty_version' => 'v9.19.0',
            'version' => '9.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/conditionable',
            'aliases' => array(),
            'reference' => '46b7beed47948bd2e67f523d0a76daa62775031e',
            'dev_requirement' => true,
        ),
        'illuminate/config' => array(
            'pretty_version' => 'v9.19.0',
            'version' => '9.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/config',
            'aliases' => array(),
            'reference' => 'd2dc74fdcc89239e1910a8d08b2b2e5ad26a043c',
            'dev_requirement' => true,
        ),
        'illuminate/container' => array(
            'pretty_version' => 'v9.19.0',
            'version' => '9.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/container',
            'aliases' => array(),
            'reference' => 'd86b073cae04713cf28def54417fa771621bc4f1',
            'dev_requirement' => true,
        ),
        'illuminate/contracts' => array(
            'pretty_version' => 'v9.19.0',
            'version' => '9.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/contracts',
            'aliases' => array(),
            'reference' => 'e014cf88ef46065b8b1f078893c01189b95ffb11',
            'dev_requirement' => true,
        ),
        'illuminate/events' => array(
            'pretty_version' => 'v9.19.0',
            'version' => '9.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/events',
            'aliases' => array(),
            'reference' => '2dea521665d295f6cefef78f1b5abeea6b94e35f',
            'dev_requirement' => true,
        ),
        'illuminate/filesystem' => array(
            'pretty_version' => 'v9.19.0',
            'version' => '9.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/filesystem',
            'aliases' => array(),
            'reference' => '0a73863f90e905d1d5053108fa2a270b2ec6fb0f',
            'dev_requirement' => true,
        ),
        'illuminate/macroable' => array(
            'pretty_version' => 'v9.19.0',
            'version' => '9.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/macroable',
            'aliases' => array(),
            'reference' => '25a2c6dac2b7541ecbadef952702e84ae15f5354',
            'dev_requirement' => true,
        ),
        'illuminate/pipeline' => array(
            'pretty_version' => 'v9.19.0',
            'version' => '9.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/pipeline',
            'aliases' => array(),
            'reference' => 'e0be3f3f79f8235ad7334919ca4094d5074e02f6',
            'dev_requirement' => true,
        ),
        'illuminate/support' => array(
            'pretty_version' => 'v9.19.0',
            'version' => '9.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/support',
            'aliases' => array(),
            'reference' => '350d65d043cd81ef84e8f5967d8935e8fa52c055',
            'dev_requirement' => true,
        ),
        'illuminate/view' => array(
            'pretty_version' => 'v9.19.0',
            'version' => '9.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/view',
            'aliases' => array(),
            'reference' => 'e1fecebacd0aebde3239eb6a037ba06a1755d257',
            'dev_requirement' => true,
        ),
        'nesbot/carbon' => array(
            'pretty_version' => '2.59.1',
            'version' => '2.59.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nesbot/carbon',
            'aliases' => array(),
            'reference' => 'a9000603ea337c8df16cc41f8b6be95a65f4d0f5',
            'dev_requirement' => true,
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'reference' => 'c71ecc56dfe541dbd90c5360474fbc405f8d5963',
            'dev_requirement' => true,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '1.1|2.0',
            ),
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'reference' => '764e0b3939f5ca87cb904f570ef9be2d78a07865',
            'dev_requirement' => true,
        ),
        'ramsey/collection' => array(
            'pretty_version' => '1.2.2',
            'version' => '1.2.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/collection',
            'aliases' => array(),
            'reference' => 'cccc74ee5e328031b15640b51056ee8d3bb66c0a',
            'dev_requirement' => false,
        ),
        'ramsey/uuid' => array(
            'pretty_version' => '4.3.1',
            'version' => '4.3.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ramsey/uuid',
            'aliases' => array(),
            'reference' => '8505afd4fea63b81a85d3b7b53ac3cb8dc347c28',
            'dev_requirement' => false,
        ),
        'rhumsaa/uuid' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '4.3.1',
            ),
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v6.1.0',
            'version' => '6.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'reference' => '45b8beb69d6eb3b05a65689ebfd4222326773f8f',
            'dev_requirement' => true,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'reference' => '9344f9cb97f3b19424af1a21a3b0e75b0a7d8d7e',
            'dev_requirement' => true,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'reference' => 'cfa0ae98841b9e461207c13ab093d76b0fa7bace',
            'dev_requirement' => true,
        ),
        'symfony/polyfill-php81' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php81',
            'aliases' => array(),
            'reference' => '13f6d1271c663dc5ae9fb843a8f16521db7687a1',
            'dev_requirement' => false,
        ),
        'symfony/translation' => array(
            'pretty_version' => 'v6.1.0',
            'version' => '6.1.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation',
            'aliases' => array(),
            'reference' => 'b254416631615bc6fe49b0a67f18658827288147',
            'dev_requirement' => true,
        ),
        'symfony/translation-contracts' => array(
            'pretty_version' => 'v3.1.1',
            'version' => '3.1.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation-contracts',
            'aliases' => array(),
            'reference' => '606be0f48e05116baef052f7f3abdb345c8e02cc',
            'dev_requirement' => true,
        ),
        'symfony/translation-implementation' => array(
            'dev_requirement' => true,
            'provided' => array(
                0 => '2.3|3.0',
            ),
        ),
        'voku/portable-ascii' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../voku/portable-ascii',
            'aliases' => array(),
            'reference' => 'b56450eed252f6801410d810c8e1727224ae0743',
            'dev_requirement' => true,
        ),
    ),
);
